name: Build NanoLimbo and upload jar to Release 

on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/java/ua/nanit/limbo/NanoLimbo.java'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar_name: ${{ steps.prepare_jar.outputs.jar_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew clean shadowJar

      - name: Prepare JAR
        id: prepare_jar
        run: |
          JAR_NAME="altr-SG-server.jar"
          JAR_PATH=$(find build/libs -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          cp "$JAR_PATH" "./$JAR_NAME"
          echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NanoLimbo-artifact
          path: "${{ steps.prepare_jar.outputs.jar_name }}"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: NanoLimbo-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ needs.build.outputs.jar_name }}"
          tag_name: ${{ github.ref_name }}
          name: "NanoLimbo ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
